# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classifiers.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from logisticresult import Ui_Form1
from decessiontreeresult import Ui_Form2
from gradientboosterresult import Ui_Form3
from randomforestresult import Ui_Form4
from passiveaggressiveresult import Ui_Form5
from viewall import Ui_Form6









class Ui_Form(object):
    def __init__(self,text1):
              self.text1=text1
    def openlogisticresult(self):
        self.Widget=QtWidgets.QWidget()
        self.ui=Ui_Form1(self.text1)
        self.ui.setupUi(self.Widget)
        self.Widget.show()
    def opendecessionresult(self):
         self.Widget=QtWidgets.QWidget()
         self.ui=Ui_Form2(self.text1)
         self.ui.setupUi(self.Widget)
         self.Widget.show()
    def opengradientresult(self):
         self.Widget=QtWidgets.QWidget()
         self.ui=Ui_Form3(self.text1)
         self.ui.setupUi(self.Widget)
         self.Widget.show()
    def openrandomforestresult(self):
         self.Widget=QtWidgets.QWidget()
         self.ui=Ui_Form4(self.text1)
         self.ui.setupUi(self.Widget)
         self.Widget.show()
    def openpassiveaggressiveresult(self):
         self.Widget=QtWidgets.QWidget()
         self.ui=Ui_Form5(self.text1)
         self.ui.setupUi(self.Widget)
         self.Widget.show()
    def openviewallresult(self):
         self.Widget=QtWidgets.QWidget()
         self.ui=Ui_Form6(self.text1)
         self.ui.setupUi(self.Widget)
         self.Widget.show()                  
              
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(571, 509)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 20, 241, 51))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 361, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 400, 161, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gradient = QtWidgets.QPushButton(Form)
        self.gradient.setGeometry(QtCore.QRect(60, 280, 161, 51))
        self.gradient.setObjectName("gradient")
        self.randomforest = QtWidgets.QPushButton(Form)
        self.randomforest.setGeometry(QtCore.QRect(280, 280, 161, 51))
        self.randomforest.setObjectName("randomforest")
        self.passiveaggresive = QtWidgets.QPushButton(Form)
        self.passiveaggresive.setGeometry(QtCore.QRect(62, 401, 161, 51))
        self.passiveaggresive.setObjectName("passiveaggresive")
        self.decessiontree = QtWidgets.QPushButton(Form)
        self.decessiontree.setGeometry(QtCore.QRect(270, 170, 171, 51))
        self.decessiontree.setObjectName("decessiontree")
        self.logestic = QtWidgets.QPushButton(Form)
        self.logestic.setGeometry(QtCore.QRect(70, 170, 151, 51))
        self.logestic.setObjectName("logestic")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.logestic.clicked.connect(self.openlogisticresult)
        self.decessiontree.clicked.connect(self.opendecessionresult)
        self.gradient.clicked.connect(self.opengradientresult)
        self.randomforest.clicked.connect(self.openrandomforestresult)
        self.passiveaggresive.clicked.connect(self.openpassiveaggressiveresult)
        self.pushButton_2.clicked.connect(self.openviewallresult)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Classifiers Window"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#f94855;\">CLASSIFIERS</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">&quot;  Click on Any Cassifier Button To View The Result  &quot;</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "View All"))
        self.gradient.setText(_translate("Form", "Gradient Boosting "))
        self.randomforest.setText(_translate("Form", "Random Forest"))
        self.passiveaggresive.setText(_translate("Form", "Passive Aggresive"))
        self.decessiontree.setText(_translate("Form", "Decision Tree"))
        self.logestic.setText(_translate("Form", "Logistic Regression"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
