# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displaywindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from subprocess import call



class Ui_form1(object):
    def openotp(self):
        call(["python", "otp.py"])
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(968, 530)
        self.label1 = QtWidgets.QLabel(form1)
        self.label1.setGeometry(QtCore.QRect(0, 0, 971, 531))
        self.label1.setText("")
        self.label1.setPixmap(QtGui.QPixmap("displayimg.png"))
        self.label1.setScaledContents(True)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(form1)
        self.label2.setGeometry(QtCore.QRect(240, 50, 581, 51))
        self.label2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label2.setLineWidth(3)
        self.label2.setObjectName("label2")
        self.pushbutton1 = QtWidgets.QPushButton(form1)
        self.pushbutton1.setGeometry(QtCore.QRect(390, 380, 151, 51))
        self.pushbutton1.setObjectName("pushbutton1")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        self.pushbutton1.clicked.connect(self.openotp)

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "Fake News Detection System"))
        self.label2.setText(_translate("form1", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; font-style:italic; color:#ffa8e9;\">FAKE NEWS </span><span style=\" font-size:36pt; font-weight:600; font-style:italic; color:#fdcd94;\">DETECTION SYSTEM</span></p></body></html>"))
        self.pushbutton1.setText(_translate("form1", "START"))
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
